return {
  require 'custom.plugins.comment',
  require 'custom.plugins.gitsigns',
  require 'custom.plugins.whichkey',
  require 'custom.plugins.telescope_config',
  require 'custom.plugins.lsp-settings',
  require 'custom.plugins.conform',
  require 'custom.plugins.cmp-settings',
  require 'custom.plugins.autopairs',
  require 'custom.plugins.lspkind-settings',
  require 'custom.plugins.pretty-comments',
  require 'custom.plugins.mini-settings',
  require 'custom.plugins.treesitter-settings',
  require 'custom.plugins.flash-settings',
  require 'custom.plugins.oil-settings',
  require 'custom.plugins.toggleterm-settings',
  require 'custom.plugins.lazygit-settings',
  -- require 'custom.plugins.catppuccin-settings',
  require 'custom.plugins.tokyonight-settings',
  require 'custom.plugins.zenmode-settings',
}
