return {
  require 'custom.plugins.comment',
  require 'custom.plugins.gitsigns',
  require 'custom.plugins.telescope_config',
  require 'custom.plugins.lsp-settings',
  require 'custom.plugins.conform',
  require 'custom.plugins.cmp-settings',
  require 'custom.plugins.autopairs',
  require 'custom.plugins.lspkind-settings',
  require 'custom.plugins.pretty-comments',
  require 'custom.plugins.mini-settings',
  require 'custom.plugins.treesitter-settings',
  require 'custom.plugins.flash-settings',
  require 'custom.plugins.oil-settings',
  require 'custom.plugins.toggleterm-settings',
  require 'custom.plugins.lazygit-settings',
  require 'custom.plugins.zenmode-settings',
  require 'custom.plugins.tailwindsort-settings',
  require 'custom.plugins.spectre-settings',
  require 'custom.plugins.lualine',
  require 'custom.plugins.trouble-settings',
  require 'custom.plugins.diffview-settings',
  require 'custom.plugins.fidget-settings',
  require 'custom.plugins.aerial-settings',
  require 'custom.plugins.tiny-inline-diagnostic-settings',
  require 'custom.plugins.go-tags-settings',
  -- require 'custom.plugins.avante', -- DISABLED: causes nvim to auto-close
  require 'custom.plugins.render-markdown',
  require 'custom.plugins.autosession-settings',
  require 'custom.plugins.autotag',
  require 'custom.plugins.neotree-settings',

  --themes

  -- require 'custom.plugins.themes.ariake-settings',
  -- require 'custom.plugins.themes.oh-lucy-settings',
  require 'custom.plugins.themes.oxocarbon-settings',
  -- require 'custom.plugins.themes.poimandres',
  -- require 'custom.plugins.themes.cyberdream-settings',
  -- require 'custom.plugins.themes.rosepine-settings',
  -- require 'custom.plugins.themes.catppuccin-settings',
  -- require 'custom.plugins.themes.nightofox-settings',
  -- require 'custom.plugins.themes.tokyonight-settings',
  -- require 'custom.plugins.themes.tokyonight-custom-settings',
}
